# Generated by Django 3.2.7 on 2022-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_faq_feature_message_notiifcation_product_project_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='ccreated_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['image', 'title', 'is_published', 'created_at', 'updated_at'], name='api_app_abo_image_326638_idx'),
        ),
    ]
