# Generated by Django 3.2.7 on 2022-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20220723_0743'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='about',
            name='api_app_abo_image_326638_idx',
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['image'], name='api_app_abo_image_913e58_idx'),
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['title'], name='api_app_abo_title_bdfbce_idx'),
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['is_published'], name='api_app_abo_is_publ_62ceaa_idx'),
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['created_at'], name='api_app_abo_created_b2e3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='about',
            index=models.Index(fields=['updated_at'], name='api_app_abo_updated_1e0b1c_idx'),
        ),
    ]
