# Generated by Django 3.2.7 on 2022-07-23 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0009_auto_20220723_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article_id'], name='api_app_art_article_cbc2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['user_id'], name='api_app_art_user_id_ad6542_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['created_at'], name='api_app_art_created_009c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['updated_at'], name='api_app_art_updated_f5c6e6_idx'),
        ),
    ]
