# Generated by Django 3.2.7 on 2022-07-23 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0010_auto_20220723_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notiifcation',
            new_name='Notification',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_user_id_b6ea5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_subject_90a08b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_sort_co_509e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_readed__f67df9_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_created_9f484d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_app_not_updated_ec324a_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id'], name='api_app_not_user_id_df6e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subject'], name='api_app_not_subject_715533_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sort_content'], name='api_app_not_sort_co_fa0043_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['readed_at'], name='api_app_not_readed__0ec384_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='api_app_not_created_7c6bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['updated_at'], name='api_app_not_updated_cf677d_idx'),
        ),
    ]
